#!/usr/bin/env osascript

on run argv
  tell application "System Events"
    set frontApp to name of first application process whose frontmost is true
    if frontApp is not "iTerm2" then
      set errorCode to item 2 of argv
      set durationInSeconds to item 3 of argv

      set notifTitle to item 1 of argv
      set notifBody to "Done in "
      if errorCode is not "0"
        set notifBody to "failed after "
      end if
      set notifBody to notifBody & durationInSeconds & " seconds"
      display notification notifBody with title notifTitle
    end if
  end tell
end run
