#!/bin/sh

branch=$(git symbolic-ref --short -q HEAD)
if [ "$branch" == "develop" ]
then
    .git/hooks/ctags >/dev/null 2>&1 &
fi

# The following is based on https://gist.github.com/sindresorhus/7996717
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
    echo "$changed_files" | grep --quiet "$1"
    if [ $? -eq 0 ]
    then
        echo ""
        echo " 👉  $1 changed! You may want to $2!"
    fi
}

check_run package.json "yarn install"
check_run composer.lock "composer install"
check_run bower.json "bower install"
check_run env.template "update your environment variables"
